
defaults: &defaults
  adapter: mysql2
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>
  username: <%= ENV.fetch('DATABASE_USERNAME', 'root') %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  encoding: utf8
  port: <%= ENV.fetch('DATABASE_PORT', 3306) %>
  local_infile: true

development:
  <<: *defaults
  database: <%= ENV.fetch('DATABASE_NAME', 'sequra') %>

test:
  <<: *defaults
  database: <%= ENV.fetch('DATABASE_NAME', 'sequra_test') %>

production:
  <<: *defaults
  database: db/production.sqlite3